weights: ''
cfg: /home/omega/workspace/FINAL-YOLO-V5-MASK-DETECTION/mask-detection-yolov5/yolov5-master/models/yolov5n.yaml
data: /home/omega/workspace/FINAL-YOLO-V5-MASK-DETECTION/mask-detection-yolov5/yolov5-master/data/custom_data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 65
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5n_results_random_initial_weights
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov5n_results_random_initial_weights2
